development:
  adapter: postgresql
  database: 'ruby_blog_database' #'REPLACE THIS WITH YOUR DATABASE NAME FROM THE PREVIOUS CODE WE HAD'
production:
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>